import Vue from 'vue';
import Router from 'vue-router';
Vue.use(Router);
/**将所有的路由都定义在一起*/
const components={
  login:()=>import('@/views/login/login') ,  /**使用异步的引入方式*/
  layout:()=>import("@/views/layout/layout"),
  index:()=>import("@/views/index/index"),
  users:()=>import("@/views/users/users"),
  addUser:()=>import("@/views/users/addUser"),
  modifyAdmin:()=>import("@/views/users/ModifyAdmin"),
  test:()=>import("@/views/test/test"),
  detail:()=>import("@/views/users/AdminDetails"),
  allSort:()=>import("@/views/books/allsort"),
  bookstore:()=>import("@/views/books/Bookstore"),
  addsort:()=>import("@/views/books/addsort"),
  addbook:()=>import("@/views/books/addBooks"),
  editsort:()=>import("@/views/books/EditSort"),
  booklist:()=>import("@/views/letters/getList"),
  editbook:()=>import("@/views/letters/editBook"),
  viewlist:()=>import("@/views/sowing/getViewList"),
  editview:()=>import("@/views/sowing/editView"),
  addview:()=>import("@/views/sowing/addView"),
  lookbook:()=>import("@/views/letters/lookBook")
};

export default new Router({
  routes: [
    {
      path:"/",
      redirect:"/login",
    },
    {
      path: '/login',
      name: 'HelloWorld',
      component:components.login,
    },
    {
      path:"/layout",
      component:components.layout,
      redirect:"/layout/index",
      children:[
        {
          path:"index",
          component:components.index,
          meta:{
            title:"首页",
          },

        },
        {
          path:"users",
          meta:{
            title:"用户管理"
          },
          component:components.users,
        },
        {
          path:"addUser",
          component:components.addUser,
          meta:{
            title:"用户添加"
          }
        },
        {
          path:"modifyAdmin",
          component:components.modifyAdmin,
          meta:{
            title:"修改管理员"
          }
        },
        {
          path:"test",
          component:components.test,
          meta:{
            title:"测试页"
          }
        },
        {
          path:"detail",
          component:components.detail,
          meta:{
            title:"管理员的详情页"
          }
        },
        {
          path:"allSort",
          component:components.allSort,
          meta:{
            title:"获取书的全部分类"
          }
        },
        {
          path:"bookstore",
          component:components.bookstore,
          meta:{
            title:"书库"
          }
        },
        {
          path:"addsort",
          component:components.addsort,
          meta:{
            title:"添加分类"
          }
        },
        {
          path:"addbook",
          component:components.addbook,
          meta:{
            title:"添加图书"
          }
        },
        {
          path:"editsort",
          component:components.editsort,
          meta:{
            title:"修改分类"
          }
        },
        {
          path:"booklist",
          component:components.booklist,
          meta:{
            title:"书籍列表"
          }
        },
        {
          path:"editBook",
          component:components.editbook,
          meta:{
            title:"图书修改"
          }
        },
        {
          path:"viewList",
          component:components.viewlist,
          meta:{
            title:"轮播图列表"
          }
        },
        {
          path:"editView",
          component:components.editview,
          meta:{
            title:"修改轮播图"
          }
        },
        {
          path:"addview",
          component:components.addview,
          meta:{
            title:"添加轮播图",
          }
        },
        {
          path:"lookBook",
          component:components.lookbook,
          meta:{
            title:"查看书籍"
          }
        }
      ]
    }
  ]
})
